name: task-tracker-dev
services:
  postgres:
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_tracker_dev
    restart: on-failure
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  kafka:
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    restart: on-failure

  task-tracker-backend:
    profiles:
      - disabled
#
  task-tracker-scheduler:
    profiles:
      - disabled

  task-tracker-email-sender:
    profiles:
      - disabled

  task-tracker-frontend:
    environment:
      BACKEND_API_URL: http://192.168.1.31:8080/
    restart: on-failure
#    profiles:
#      - disabled

volumes:
  postgres_data_dev: