name: task-tracker-dev
services:
  postgres:
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_tracker_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  kafka:
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  task-tracker-backend:
    profiles:
      - disabled
#
#  task-tracker-scheduler:
#    profiles:
#      - disabled
#
#  task-tracker-email-sender:
#    profiles:
#      - disabled
#
#  task-tracker-frontend:
#    profiles:
#      - disabled

volumes:
  postgres_data_dev: