services:
  postgres:
    image: postgres:17.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

  zookeeper:
    image: bitnami/zookeeper:3.9.3
    environment:
      ZOO_ENABLE_AUTH: "no"
      ALLOW_ANONYMOUS_LOGIN: "yes"
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.9.0
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_BOOTSTRAP_SERVERS}
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    restart: unless-stopped

  task-tracker-backend:
    image: ${DOCKERHUB_USERNAME}/task-tracker-backend:latest
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER_URI: ${JWT_ISSUER_URI}
      JWT_EXPIRATION_SECONDS: ${JWT_EXPIRATION_SECONDS}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC_EMAIL_SENDING: ${KAFKA_TOPIC_EMAIL_SENDING}
    depends_on:
      - postgres
      - kafka
    restart: unless-stopped

  task-tracker-scheduler:
    image: ${DOCKERHUB_USERNAME}/task-tracker-scheduler:latest
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC_EMAIL_SENDING: ${KAFKA_TOPIC_EMAIL_SENDING}
    depends_on:
      - postgres
      - kafka
    restart: unless-stopped

  task-tracker-email-sender:
    image: ${DOCKERHUB_USERNAME}/task-tracker-email-sender:latest
    environment:
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TOPIC_EMAIL_SENDING: ${KAFKA_TOPIC_EMAIL_SENDING}
      KAFKA_GROUP_EMAIL_SENDER: ${KAFKA_GROUP_EMAIL_SENDER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_VERIFIED_EMAIL: ${MAIL_VERIFIED_EMAIL}
    depends_on:
      - kafka
    restart: unless-stopped

  task-tracker-frontend:
    image: ${DOCKERHUB_USERNAME}/task-tracker-frontend:latest
    ports:
      - "80:80"
    environment:
      BACKEND_API_URL: http://task-tracker-backend:8080/
    restart: unless-stopped

volumes:
  postgres_data_prod: